# Generated by Django 5.1.2 on 2025-10-28 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DodeljujanjeNagrade',
            fields=[
                ('iddg', models.AutoField(db_column='iddg', primary_key=True, serialize=False)),
                ('datdodele', models.DateField(db_column='datdodele')),
            ],
            options={
                'verbose_name': 'Dodeljivanje nagrade',
                'verbose_name_plural': 'Dodeljivanja nagrada',
                'db_table': 'dodeljivanje_nagrade',
            },
        ),
        migrations.CreateModel(
            name='Drzava',
            fields=[
                ('iddr', models.AutoField(db_column='iddr', primary_key=True, serialize=False)),
                ('nazdr', models.CharField(db_column='nazdr', max_length=20)),
                ('prvagoduc', models.IntegerField(db_column='prvagoduc', validators=[django.core.validators.MinValueValidator(1900)])),
                ('brpob', models.IntegerField(db_column='brpob', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Država',
                'verbose_name_plural': 'Zemlje',
                'db_table': 'drzava',
            },
        ),
        migrations.CreateModel(
            name='Duo',
            fields=[
                ('idduo', models.AutoField(db_column='idduo', primary_key=True, serialize=False)),
                ('nazduo', models.CharField(db_column='nazduo', max_length=20)),
            ],
            options={
                'verbose_name': 'Duo',
                'verbose_name_plural': 'Duosi',
                'db_table': 'duo',
            },
        ),
        migrations.CreateModel(
            name='Dvorana',
            fields=[
                ('iddv', models.AutoField(db_column='iddv', primary_key=True, serialize=False)),
                ('nazdv', models.CharField(db_column='nazdv', max_length=20)),
                ('kap', models.IntegerField(db_column='kap', validators=[django.core.validators.MinValueValidator(1)])),
                ('grad', models.CharField(db_column='grad', max_length=20)),
                ('drz', models.CharField(db_column='drz', max_length=20)),
            ],
            options={
                'verbose_name': 'Dvorana',
                'verbose_name_plural': 'Dvorane',
                'db_table': 'dvorana',
            },
        ),
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('idg', models.AutoField(db_column='idg', primary_key=True, serialize=False)),
                ('nazg', models.CharField(db_column='nazg', max_length=20)),
                ('brclang', models.IntegerField(db_column='brclang', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupe',
                'db_table': 'grupa',
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idk', models.AutoField(db_column='idk', primary_key=True, serialize=False)),
                ('imek', models.CharField(db_column='imek', max_length=20)),
                ('przk', models.CharField(db_column='przk', max_length=30)),
                ('mejl', models.EmailField(db_column='mejl', max_length=254, unique=True)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('lozinka', models.CharField(db_column='lozinka', max_length=255)),
                ('tipk', models.CharField(choices=[('UCESNIK', 'Učesnik'), ('SUDIJA', 'Sudija'), ('ORGANIZATOR', 'Organizator')], db_column='tipk', default='UCESNIK', max_length=15)),
            ],
            options={
                'verbose_name': 'Korisnik',
                'verbose_name_plural': 'Korisnici',
                'db_table': 'korisnik',
            },
        ),
        migrations.CreateModel(
            name='MuzickoTakmicenje',
            fields=[
                ('idmt', models.AutoField(db_column='idmt', primary_key=True, serialize=False)),
                ('nazmt', models.CharField(db_column='nazmt', max_length=30)),
                ('godosn', models.DateField(db_column='godosn')),
            ],
            options={
                'verbose_name': 'Muzičko takmičenje',
                'verbose_name_plural': 'Muzička takmičenja',
                'db_table': 'muzicko_takmicenje',
            },
        ),
        migrations.CreateModel(
            name='Pesma',
            fields=[
                ('idp', models.AutoField(db_column='idp', primary_key=True, serialize=False)),
                ('nazp', models.CharField(db_column='nazp', max_length=20)),
                ('trajanje', models.IntegerField(db_column='trajanje', validators=[django.core.validators.MinValueValidator(0)])),
                ('datob', models.DateField(db_column='datob')),
            ],
            options={
                'verbose_name': 'Pesma',
                'verbose_name_plural': 'Pesme',
                'db_table': 'pesma',
            },
        ),
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('ids', models.AutoField(db_column='ids', primary_key=True, serialize=False)),
                ('umime', models.CharField(db_column='umime', max_length=20)),
            ],
            options={
                'verbose_name': 'Solo',
                'verbose_name_plural': 'Solisti',
                'db_table': 'solo',
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('idzanr', models.AutoField(db_column='idzanr', primary_key=True, serialize=False)),
                ('nazzanr', models.CharField(db_column='nazzanr', max_length=15)),
            ],
            options={
                'verbose_name': 'Žanr',
                'verbose_name_plural': 'Žanrovi',
                'db_table': 'zanr',
            },
        ),
        migrations.CreateModel(
            name='Ziri',
            fields=[
                ('idz', models.AutoField(db_column='idz', primary_key=True, serialize=False)),
                ('brclanz', models.IntegerField(db_column='brclanz', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Žiri',
                'verbose_name_plural': 'Žiriji',
                'db_table': 'ziri',
            },
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('idk', models.OneToOneField(db_column='idk', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.korisnik')),
                ('dat_registracije', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Organizator',
                'verbose_name_plural': 'Organizatori',
                'db_table': 'organizator',
            },
        ),
        migrations.CreateModel(
            name='Sudija',
            fields=[
                ('idk', models.OneToOneField(db_column='idk', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.korisnik')),
                ('titula', models.CharField(db_column='titula', max_length=20)),
                ('dat_registracije', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Sudija',
                'verbose_name_plural': 'Sudije',
                'db_table': 'sudija',
            },
        ),
        migrations.CreateModel(
            name='Izdanje',
            fields=[
                ('idizd', models.AutoField(db_column='idizd', primary_key=True, serialize=False)),
                ('datpoc', models.DateField(db_column='datpoc')),
                ('datkraj', models.DateField(db_column='datkraj')),
                ('muzicko_takmicenje', models.ForeignKey(db_column='muzicko_takmicenje_idmt', on_delete=django.db.models.deletion.CASCADE, related_name='izdanja', to='api.muzickotakmicenje')),
                ('ziri', models.ForeignKey(blank=True, db_column='ziri_idz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ziri')),
            ],
            options={
                'verbose_name': 'Izdanje',
                'verbose_name_plural': 'Izdanja',
                'db_table': 'izdanje',
            },
        ),
        migrations.CreateModel(
            name='Nagrada',
            fields=[
                ('idnag', models.AutoField(db_column='idnag', primary_key=True, serialize=False)),
                ('naznag', models.CharField(db_column='naznag', max_length=20)),
                ('dodeljivanje_nagrade', models.ForeignKey(blank=True, db_column='dodeljivanje_nagrade_iddg', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nagrade', to='api.dodeljujanjenagrade')),
            ],
            options={
                'verbose_name': 'Nagrada',
                'verbose_name_plural': 'Nagrade',
                'db_table': 'nagrada',
            },
        ),
        migrations.CreateModel(
            name='SeOdrzava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvorana', models.ForeignKey(db_column='dvorana_iddv', on_delete=django.db.models.deletion.CASCADE, related_name='izdanja_odrzana', to='api.dvorana')),
                ('izdanje', models.ForeignKey(db_column='izdanje_idizd', on_delete=django.db.models.deletion.CASCADE, related_name='dvorane_odrzavanja', to='api.izdanje')),
            ],
            options={
                'verbose_name': 'Održava se',
                'verbose_name_plural': 'Održavanja',
                'db_table': 'se_odrzava',
                'unique_together': {('dvorana', 'izdanje')},
            },
        ),
        migrations.AddField(
            model_name='dvorana',
            name='izdanja',
            field=models.ManyToManyField(related_name='dvorane', through='api.SeOdrzava', to='api.izdanje'),
        ),
        migrations.CreateModel(
            name='TakmickarsKrug',
            fields=[
                ('idtk', models.AutoField(db_column='idtk', primary_key=True, serialize=False)),
                ('rbrtk', models.IntegerField(db_column='rbrtk', validators=[django.core.validators.MinValueValidator(1)])),
                ('datodrz', models.DateField(db_column='datodrz')),
                ('izdanje', models.ForeignKey(db_column='izdanje_idizd', on_delete=django.db.models.deletion.CASCADE, related_name='takmickarski_krugovi', to='api.izdanje')),
                ('parent_krug', models.ForeignKey(blank=True, db_column='takmicarski_krug_idtk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_krugovi', to='api.takmickarskrug')),
            ],
            options={
                'verbose_name': 'Takmičarski krug',
                'verbose_name_plural': 'Takmički krugovi',
                'db_table': 'takmicarski_krug',
            },
        ),
        migrations.CreateModel(
            name='Nastup',
            fields=[
                ('idn', models.AutoField(db_column='idn', primary_key=True, serialize=False)),
                ('ukbod', models.IntegerField(db_column='ukbod', validators=[django.core.validators.MinValueValidator(0)])),
                ('rbrn', models.IntegerField(db_column='rbrn', validators=[django.core.validators.MinValueValidator(1)])),
                ('plasman', models.IntegerField(db_column='plasman', validators=[django.core.validators.MinValueValidator(1)])),
                ('dodeljivanje_nagrade', models.ForeignKey(blank=True, db_column='dodeljivanje_nagrade_iddg', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nastupe', to='api.dodeljujanjenagrade')),
                ('drzava', models.ForeignKey(db_column='drzava_iddr', on_delete=django.db.models.deletion.PROTECT, related_name='nastupe', to='api.drzava')),
                ('pesma', models.ForeignKey(db_column='pesma_idp', on_delete=django.db.models.deletion.PROTECT, related_name='nastupe', to='api.pesma')),
                ('takmickarski_krug', models.ForeignKey(db_column='takmicarski_krug_idtk', on_delete=django.db.models.deletion.CASCADE, related_name='nastupe', to='api.takmickarskrug')),
            ],
            options={
                'verbose_name': 'Nastup',
                'verbose_name_plural': 'Nastupi',
                'db_table': 'nastup',
            },
        ),
        migrations.CreateModel(
            name='Ucestvuje',
            fields=[
                ('ucestvuje_id', models.AutoField(db_column='ucestvuje_id', primary_key=True, serialize=False)),
                ('drzava', models.ForeignKey(db_column='drzava_iddr', on_delete=django.db.models.deletion.CASCADE, related_name='ucestva', to='api.drzava')),
                ('izdanje', models.ForeignKey(db_column='izdanje_idizd', on_delete=django.db.models.deletion.CASCADE, related_name='ucestva', to='api.izdanje')),
            ],
            options={
                'verbose_name': 'Učešće',
                'verbose_name_plural': 'Učešća',
                'db_table': 'ucestvuje',
                'unique_together': {('izdanje', 'drzava')},
            },
        ),
        migrations.AddField(
            model_name='pesma',
            name='zanr',
            field=models.ForeignKey(db_column='zanr_idzanr', on_delete=django.db.models.deletion.PROTECT, to='api.zanr'),
        ),
        migrations.CreateModel(
            name='SastojSe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predsednik', models.BooleanField(db_column='predsednik', default=False)),
                ('ziri', models.ForeignKey(db_column='ziri_idz', on_delete=django.db.models.deletion.CASCADE, related_name='sudije_sastava', to='api.ziri')),
                ('sudija', models.ForeignKey(db_column='sudija_idk', on_delete=django.db.models.deletion.CASCADE, related_name='ziri_sastavljivanja', to='api.sudija')),
            ],
            options={
                'verbose_name': 'Sastoji se',
                'verbose_name_plural': 'Sastavnice',
                'db_table': 'sastoji_se',
                'unique_together': {('ziri', 'sudija')},
            },
        ),
        migrations.CreateModel(
            name='Organizuje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muzicko_takmicenje', models.ForeignKey(db_column='muzicko_takmicenje_idmt', on_delete=django.db.models.deletion.CASCADE, related_name='organizovano_od', to='api.muzickotakmicenje')),
                ('organizator', models.ForeignKey(db_column='organizator_idk', on_delete=django.db.models.deletion.CASCADE, related_name='organizuje', to='api.organizator')),
            ],
            options={
                'verbose_name': 'Organizuje',
                'verbose_name_plural': 'Organizovanja',
                'db_table': 'organizuje',
                'unique_together': {('organizator', 'muzicko_takmicenje')},
            },
        ),
        migrations.AddField(
            model_name='muzickotakmicenje',
            name='organizator',
            field=models.ManyToManyField(related_name='muzicka_takmicenja', through='api.Organizuje', to='api.organizator'),
        ),
        migrations.AddField(
            model_name='ziri',
            name='sudija',
            field=models.ManyToManyField(related_name='ziri', through='api.SastojSe', to='api.sudija'),
        ),
        migrations.AddField(
            model_name='dodeljujanjenagrade',
            name='sudija',
            field=models.ForeignKey(db_column='sudija_idk', on_delete=django.db.models.deletion.PROTECT, related_name='dodeljivanja_nagrada', to='api.sudija'),
        ),
        migrations.CreateModel(
            name='Ucesnik',
            fields=[
                ('idk', models.OneToOneField(db_column='idk', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.korisnik')),
                ('tipu', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('GRUPA', 'Grupa')], db_column='tipu', max_length=10)),
                ('dat_dodeljivanja', models.DateTimeField(auto_now_add=True, null=True)),
                ('dodat_od', models.ForeignKey(blank=True, help_text='Organizator koji je dodao ovog učesnika', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dodeljeni_ucesnici', to='api.korisnik')),
                ('duo', models.OneToOneField(blank=True, db_column='duo_idduo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.duo')),
                ('grupa', models.OneToOneField(blank=True, db_column='grupa_idg', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grupa')),
                ('solo', models.OneToOneField(blank=True, db_column='solo_ids', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.solo')),
            ],
            options={
                'verbose_name': 'Učesnik',
                'verbose_name_plural': 'Učesnici',
                'db_table': 'ucesnik',
            },
        ),
        migrations.CreateModel(
            name='Dodeljuje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izdanje', models.ForeignKey(db_column='izdanje_idizd', on_delete=django.db.models.deletion.CASCADE, related_name='dodeljuje', to='api.izdanje')),
                ('nagrada', models.ForeignKey(db_column='nagrada_idnag', on_delete=django.db.models.deletion.CASCADE, related_name='dodeljeno_u_izdanju', to='api.nagrada')),
            ],
            options={
                'verbose_name': 'Dodeljuje',
                'verbose_name_plural': 'Dodeljavanja',
                'db_table': 'dodeljuje',
                'unique_together': {('izdanje', 'nagrada')},
            },
        ),
        migrations.CreateModel(
            name='Ocenjuje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bod', models.IntegerField(db_column='bod', validators=[django.core.validators.MinValueValidator(0)])),
                ('nastup', models.ForeignKey(db_column='nastup_idn', on_delete=django.db.models.deletion.CASCADE, related_name='ocene', to='api.nastup')),
                ('sudija', models.ForeignKey(db_column='sudija_idk', on_delete=django.db.models.deletion.CASCADE, related_name='ocene', to='api.sudija')),
            ],
            options={
                'verbose_name': 'Ocenjuje',
                'verbose_name_plural': 'Ocene',
                'db_table': 'ocenjuje',
                'unique_together': {('nastup', 'sudija')},
            },
        ),
        migrations.CreateModel(
            name='Reprezentuje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucestvuje', models.ForeignKey(db_column='ucestvuje_ucestvuje_id', on_delete=django.db.models.deletion.CASCADE, related_name='reprezentacije', to='api.ucestvuje')),
                ('ucesnik', models.ForeignKey(db_column='ucesnik_idk', on_delete=django.db.models.deletion.CASCADE, related_name='reprezentuje', to='api.ucesnik')),
            ],
            options={
                'verbose_name': 'Reprezentuje',
                'verbose_name_plural': 'Reprezentacije',
                'db_table': 'reprezentuje',
                'unique_together': {('ucestvuje', 'ucesnik')},
            },
        ),
        migrations.CreateModel(
            name='Izvodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesma', models.ForeignKey(db_column='pesma_idp', on_delete=django.db.models.deletion.CASCADE, related_name='izvode', to='api.pesma')),
                ('ucesnik', models.ForeignKey(db_column='ucesnik_idk', on_delete=django.db.models.deletion.CASCADE, related_name='izvodi', to='api.ucesnik')),
            ],
            options={
                'verbose_name': 'Izvodi',
                'verbose_name_plural': 'Izvedbe',
                'db_table': 'izvodi',
                'unique_together': {('ucesnik', 'pesma')},
            },
        ),
    ]
